### PR TITLE
move GetADOPSHeader to general mock folder.

### PR DESCRIPTION
**Pull request by nilsson-jens**
## Overview/Summary

Plausible solution for issue #13.
Moving specific Mocks to files in Tests/Mocks
Adding parameters to Mock files if needed and refering to them in tests like:
. "$PSScriptRoot\Mocks\GetADOPSHeader.mock.ps1" -OrganizationName $OrganizationName

Feedback Needed.

## This PR fixes/adds/changes/removes

1. GetADOPSHeader.mock.ps1
2. New-ADOPSPipeline.Tests.ps1

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/ADOPS/ADOPS/pulls)
- [x] Associated it with relevant [issues](https://github.com/ADOPS/ADOPS/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/ADOPS/ADOPS/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by bjompen** [comment]
I really like the structure of this. Makes it really easy to have consistency in mocks and if we need to change the behaviour of a mock we only need to change it once.

Does the mock inject properly in the tests? If so I absolutely approve it.

@JohnRoos , you have any opinions?

**Comment by PalmEmanuel** [comment]
Assuming it works well with the right Pester scopes I also really like the structure!

**Comment by nilsson-jens** [comment]
According to my tests, as long as you add the mock reference in the correct scope it should work.
But a second pair of eyes to validate would be good.

**Comment by bjompen** [comment]
This is now too old to merge, but I will steal the ideas for release 1.1.1.

**Pull request closed without merging**
