### PR TITLE
add Function New-ADOPSPipeline Tests and Docs.

### PR DESCRIPTION
**Pull request by nilsson-jens**
# Overview/Summary

Adds Function New-ADOPSPipeline to create a pipeline from a yaml file in a project.
Connected to Issue #68 

## This PR fixes/adds/changes/removes

1. Add function New-ADOPSPipeline.ps1
2. Add tests New-ADOPSPipeline.tests.ps1
3. Add docs New-ADOPSPipeline.md

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/bjompen/AZDOPS/pulls)
- [X] Associated it with relevant [issues](https://github.com/bjompen/AZDOPS/issues), for tracking and closure.
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/bjompen/AZDOPS/tree/main)
- [X] Performed testing and provided evidence.
- [X] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by nilsson-jens** [comment]
Needs feedback on parameter names: YamlPath and PipelineGroupFolder.
Also does it need PipelineGroupFolder?

**Comment by bjompen** [comment]
From my google findings it appears to be needed in the body, but can be set to $null or '\'
What is the behavioural difference if you set it to something vs. if you leave it empty vs. if you replave the variable with $null in the body? Do we see a usecase where we want to set it to something different?
If there is no reason to change it, remove it for now and we may add it if there is a future request for it instead, otherwise keep it as is.

**Comment by nilsson-jens** [comment]
Yes you are correct you need to pass "folder" in the json body but you can just pass in "\" if you don't need the folder in the DevOps pipeline structure. 
It's not hard to remove or add I was just thinking it might be confusing to the end user with two param names like Path and Folder. 
YamlPath and PipelineGroupFolder was the best I could come up with to avoid confusion.
We might consider to remove PipelineGroupFolder to avoid confusion and just keep default to "\".

**Comment by StefanIvemo** [comment]
Can `-FolderPath` be a good name for the param?

**Comment by nilsson-jens** [comment]
Keeping the same naming convention as az cli, I like it! -FolderPath it is!

**Comment by bjompen** [comment]
Perfect! Looks good and is in parity with the CLI - Merged!

**Review by bjompen — APPROVED** [review]

**Pull request merged**
