### PR TITLE
`Get-ADOPSPipelineSettings` / `Set-ADOPSPipelineSettings`

### PR DESCRIPTION
**Pull request by coolhome**
## Overview/Summary

```ps1

# Get Pipeline Settings
Get-ADOPSPipelineSettings -Project 'MyProject'

# Set Single Setting
Set-ADOPSPipelineSettings -Project 'MyProject' -Values @{
    enforceReferencedRepoScopedToken = $true
}

# Set Multiple Settings
Set-ADOPSPipelineSettings -Project 'MyProject' -Values @{
    enforceReferencedRepoScopedToken                  = $true
    disableClassicPipelineCreation                    = $true
    disableClassicBuildPipelineCreation               = $true
    disableClassicReleasePipelineCreation             = $true
    forkProtectionEnabled                             = $true
    buildsEnabledForForks                             = $true
    enforceJobAuthScopeForForks                       = $true
    enforceNoAccessToSecretsFromForks                 = $true
    isCommentRequiredForPullRequest                   = $true
    requireCommentsForNonTeamMembersOnly              = $false
    requireCommentsForNonTeamMemberAndNonContributors = $false
    enableShellTasksArgsSanitizing                    = $true
    enableShellTasksArgsSanitizingAudit               = $false
    disableImpliedYAMLCiTrigger                       = $true
    statusBadgesArePrivate                            = $true
    enforceSettableVar                                = $true
    enforceJobAuthScope                               = $true
    enforceJobAuthScopeForReleases                    = $true
    publishPipelineMetadata                           = $true
}
```

## This PR fixes/adds/changes/removes

1. Added cmdlet `Get-ADOPSPipelineSettings -Project $Project` to retrieve pipeline setting
2. Added cmdlet `Set-ADOPSPipelineSettings -Project -Name -Values @{ $SettingName = $SettingValue; }`

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/ADOPS/ADOPS/pulls)
- [ ] Associated it with relevant [issues](https://github.com/ADOPS/ADOPS/issues), for tracking and closure.
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/ADOPS/ADOPS/tree/main)
- [X] Performed testing and provided evidence.
- [ ] Verified build scripts work.
- [X] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by bjompen** [comment]
Awesome contribution! Thanks a lot!
My only question would be if it is needed to have both value and values as parameters if it works just as well to give a single key hashtable? I am absolutely willing to be convinced though 😉

**Comment by coolhome** [comment]
@bjompen I was thinking since this overload `Get-ADOPSPIpelineSettings -Project $Project -Name $Name` returns a single value that it would be more intuitive that changing the verb and adding $Value `Set-ADOPSPIpelineSettings -Project $Project -Name $Name -Value $Value`.

I'm okay with removing this parameter set for single value on `Set-ADOPSPIpelineSettings` and even on `Get-ADOPSPIpelineSettings`. I honestly would rather make one call than several Get/Set.

```ps1
$settings = Get-ADOPSPipelineSettings -Project MyProject
$settings.statusBadgesArePrivate = $true

Set-ADOPSPipelineSettings -Project MyProject $settings
```

Just let me know which direction :)

**Comment by bjompen** [comment]
I do like the `get -> change -> push` way. Looks clean and clear.
I am ok with the explanation, and have no issues merging as is, as long as we have a default parameter set (as in the review comment.)
Change if you want to, just let me know (I am stealing this and putting it to use already 😂)

**Comment by coolhome** [comment]
@bjompen I removed the single parameter set from get/set. I think it's GTG.

**Comment by coolhome** [comment]
@bjompen Actually I think we should consider a rename:

`ADOPSPipelineSettings` to become `ADOPSProjectPipelineSettings` which would complement `ADOPSProjectRetentionSettings`

Then introduce `Set-ADOPSPipelineSettings` (PATCH Build/Definitions/:id) to update the pipeline definition that matches the UX of Azure DevOps:
image

image

**Comment by bjompen** [comment]
Since these settings are project scoped, That rename absolutely makes sense, and renaming before releases makes a lot of sense (less major bumps!)
Go ahead and change it!

**Comment by bjompen** [comment]
Any updates on this?

**Comment by coolhome** [comment]
@bjompen I have majority of the changes ready locally, going to push both PRs tonight for review! 🚀

**Comment by coolhome** [comment]
This is ready for review. I opted out of changing the name for now. Feel free to make any changes 🥅

**Review by bjompen — APPROVED** [review]

**Pull request merged**
