### PR TITLE
Add support for PipelinePermissions

### LINKED ISSUE #185: New commands: `Grant-ADOPSPipelinePermission` and `Revoke-ADOPSPipelinePermission`
**Is your feature request related to a problem? Please describe.**
I want a command representing the [pipelinepermissions endpoint](https://learn.microsoft.com/en-us/rest/api/azure/devops/approvalsandchecks/pipeline-permissions/update-pipeline-permisions-for-resource?view=azure-devops-rest-7.0&tabs=HTTP). 

My primary use case is to give a pipeline permissions to a variable group, but it should be able to grant access to other resources as well.

**Describe the solution you'd like**
I want a command that accepts a pipeline name or id, a resource type and resource id.

Example:
`Grant-ADOPSPipelinePermission -PipelineId 16 -ResourceType variablegroup -ResourceId 42`

ResourceType should be an enum containing valid values.

**Additional context**
Might be nice with an additional parameter set that has the switch parameter -AllPipelines instead of -PipelineId

### PR DESCRIPTION
**Pull request by SimonWahlin**
## Overview/Summary

Add new commands for Grant/Revoke/Set-ADOPSPipelinePermission

## This PR fixes/adds/changes/removes

1. Add new commands for Grant/Revoke/Set-ADOPSPipelinePermission (Fixes #185)

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/ADOPS/ADOPS/pulls)
- [x] Associated it with relevant [issues](https://github.com/ADOPS/ADOPS/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/ADOPS/ADOPS/tree/main)
- [x] Performed testing and provided evidence.
- [x] Verified build scripts work.
- [x] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by SimonWahlin** [comment]
I need to document the commands, I'll fix that before we can merge but would be glad if I could get a review on the code in the meantime.

**Comment by bjompen** [comment]
Two thoughts (very much open for discussion, I have no strict opinions 😉)
- Should we set a DefaultParameterSet? It is'nt needed, but for clarity? Might make it easier to read is my thought.
- Should we maybe have Set-ADOPSPipelinePermission as an internal function? As this command doesn't serve any purpose apart from being called by Grant/Revoke it might be better to have it as internal. It would make it easier to document and test as we don't have to support the Set command per se, and also it prevents confusion by having two commands doing the same thing.

**Comment by bjompen** [comment]
Another thing: Even though it works, could you please bump API version to 7.1-preview.1? According to the docs, 7.0 is still only for PAT basic auth (OAuth seems to work anyway, but who knows..). Since we're moving towards 2.0 and OAuth 7.1 is probably better to use just to be sure everything works.

**Comment by SimonWahlin** [comment]
> Two thoughts (very much open for discussion, I have no strict opinions 😉)
> - Should we set a DefaultParameterSet? It is'nt needed, but for clarity? Might make it easier to read is my thought.

DefaultParameterSet will have no effect at all as long as there are no ambiguous sets. I can add it if you think it looks good when looking at the code, but I don't understand what clarity it brings.

> - Should we maybe have Set-ADOPSPipelinePermission as an internal function? As this command doesn't serve any purpose apart from being called by Grant/Revoke it might be better to have it as internal. It would make it easier to document and test as we don't have to support the Set command per se, and also it prevents confusion by having two commands doing the same thing.

Yes, that is probably for the best, I couldn't decide when I wrote it but in hindsight I think a private Set function is better. I'll fix that.

**Review by bjompen — APPROVED** [review]
lgtm!

**Pull request merged**
