### PR TITLE
Get-ADOPSUser

### LINKED ISSUE #113: Get-ADOPSUser
We need a feature to search for users using
- Username
- Displayname
- GUID / User ID

### PR DESCRIPTION
**Pull request by krokofant**
## Overview/Summary

fixes #113 

## This PR adds

1. Command `Get-ADOPSUser`

You can now find users by name, displayname, email or by descriptor

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/ADOPS/ADOPS/pulls)
- [X] Associated it with relevant [issues](https://github.com/ADOPS/ADOPS/issues), for tracking and closure.
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/ADOPS/ADOPS/tree/main)
- [x] Performed testing and provided evidence.
- [x] Verified build scripts work.
- [X] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by bjompen** [comment]
Thank you very much for your contribution!
Would it be possible to add a third scenario? Given no input, `Get-ADOPSUser`, return all users?
Other than that, 100% approved!

**Comment by bjompen** [comment]
This looks like a great solution! Much cleaner than what I would have written.. Please, go ahead!
(We need to add a test for i t as well, but the current working plan is get 1.1.0 out, then do a test refactor round before moving on)

**Comment by krokofant** [comment]
@bjompen Please review when you have the time

**Review by bjompen — APPROVED** [review]
Looks great! 

Bonus thank you: I have not seen $PesterBoundParameters before! More cool stuff to learn. 
Jakub does some serious magic awesome stuff :D

Merged!

**Pull request merged**
